"""remove notification_tags

Revision ID: 41395873f49e
Revises: b2c3d4e5f6g7
Create Date: 2026-07-30 10:52:50.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41395873f49e'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_memberships', 'notification_tags')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_memberships', sa.Column('notification_tags', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
