"""add assignee_id to agent_actions

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2026-07-04 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema migration: add assignee_id foreign key column to agent_actions table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_actions', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_agent_actions_assignee_id'), 'agent_actions', ['assignee_id'], unique=False)
    op.create_foreign_key(None, 'agent_actions', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema migration: remove assignee_id column and foreign key constraint."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_actions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_actions_assignee_id'), table_name='agent_actions')
    op.drop_column('agent_actions', 'assignee_id')
    # ### end Alembic commands ###

